version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    container_name: job_listings_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "9000:9000"
    working_dir: /var/www/html

  nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
    networks:
      - backend
    ports:
      - "8010:80"
    volumes:
      - ./backend:/var/www/html

  db:
    build:
      context: ./backend
      dockerfile: docker/mysql/Dockerfile
    container_name: job_listings_db
    platform: linux/amd64
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: job_listings
      MYSQL_USER: job_listings
      MYSQL_PASSWORD: job_listings
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./backend/docker/mysql/data:/var/lib/mysql/
    networks:
      - backend

  vue:
    build:
      context: .
      dockerfile: backend/docker/vue/Dockerfile
    container_name: job_vue
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]

networks:
  backend:


volumes:
  db:
    driver: local
